[package]
name = "aster-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Hand-written lexer, AST, and parser for Aster"

[dependencies]
aster-diagnostics = { path = "../aster-diagnostics", version = "0.2.0" }

[lints]
workspace = true
