[package]
name = "aster-mir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Typed mid-level intermediate representation for Aster"

[dependencies]
aster-hir = { path = "../aster-hir", version = "0.54.4" }

[lints]
workspace = true
