[package]
name = "aster-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line interface for the Aster compiler"

[[bin]]
name = "aster"
path = "src/main.rs"

[dependencies]
aster-codegen-cranelift = { path = "../aster-codegen-cranelift", version = "0.48.3" }
aster-compiler = { path = "../aster-compiler", version = "0.48.3" }

[lints]
workspace = true
