use aster_diagnostics::Span;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Public,
    Internal,
    Protected,
    Private,
    Static,
    Class,
    Struct,
    Interface,
    Enum,
    Namespace,
    Using,
    /// Legacy spelling retained only to produce a migration diagnostic.
    Module,
    /// Legacy spelling retained only to produce a migration diagnostic.
    Import,
    Const,
    Var,
    Void,
    Bool,
    SByte,
    Byte,
    Short,
    UShort,
    Int,
    UInt,
    Long,
    ULong,
    Float,
    Double,
    Decimal,
    Char,
    String,
    Return,
    If,
    Else,
    While,
    For,
    Break,
    Continue,
    Switch,
    Case,
    Default,
    New,
    This,
    True,
    False,
    Identifier(String),
    IntegerLiteral(String),
    LongLiteral(String),
    UIntLiteral(String),
    ULongLiteral(String),
    FloatLiteral(String),
    DoubleLiteral(String),
    DecimalLiteral(String),
    StringLiteral(String),
    CharacterLiteral(char),
    LeftBrace,
    RightBrace,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Comma,
    Colon,
    Semicolon,
    Dot,
    Question,
    Plus,
    PlusPlus,
    Minus,
    MinusMinus,
    Star,
    Slash,
    Percent,
    Bang,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    EqualEqual,
    BangEqual,
    AndAnd,
    OrOr,
    Equal,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    Eof,
}

impl TokenKind {
    #[must_use]
    pub fn description(&self) -> &'static str {
        match self {
            Self::Public => "`public`",
            Self::Internal => "`internal`",
            Self::Protected => "`protected`",
            Self::Private => "`private`",
            Self::Static => "`static`",
            Self::Class => "`class`",
            Self::Struct => "`struct`",
            Self::Interface => "`interface`",
            Self::Enum => "`enum`",
            Self::Namespace => "`namespace`",
            Self::Using => "`using`",
            Self::Module => "`module`",
            Self::Import => "`import`",
            Self::Const => "`const`",
            Self::Var => "`var`",
            Self::Void => "`void`",
            Self::Bool => "`bool`",
            Self::SByte => "`sbyte`",
            Self::Byte => "`byte`",
            Self::Short => "`short`",
            Self::UShort => "`ushort`",
            Self::Int => "`int`",
            Self::UInt => "`uint`",
            Self::Long => "`long`",
            Self::ULong => "`ulong`",
            Self::Float => "`float`",
            Self::Double => "`double`",
            Self::Decimal => "`decimal`",
            Self::Char => "`char`",
            Self::String => "`string`",
            Self::Return => "`return`",
            Self::If => "`if`",
            Self::Else => "`else`",
            Self::While => "`while`",
            Self::For => "`for`",
            Self::Break => "`break`",
            Self::Continue => "`continue`",
            Self::Switch => "`switch`",
            Self::Case => "`case`",
            Self::Default => "`default`",
            Self::New => "`new`",
            Self::This => "`this`",
            Self::True => "`true`",
            Self::False => "`false`",
            Self::Identifier(_) => "identifier",
            Self::IntegerLiteral(_) => "integer literal",
            Self::LongLiteral(_) => "long integer literal",
            Self::UIntLiteral(_) => "unsigned integer literal",
            Self::ULongLiteral(_) => "unsigned long literal",
            Self::FloatLiteral(_) => "floating-point literal",
            Self::DoubleLiteral(_) => "double-precision literal",
            Self::DecimalLiteral(_) => "decimal literal",
            Self::StringLiteral(_) => "string literal",
            Self::CharacterLiteral(_) => "character literal",
            Self::LeftBrace => "`{`",
            Self::RightBrace => "`}`",
            Self::LeftParen => "`(`",
            Self::RightParen => "`)`",
            Self::LeftBracket => "`[`",
            Self::RightBracket => "`]`",
            Self::Comma => "`,`",
            Self::Colon => "`:`",
            Self::Semicolon => "`;`",
            Self::Dot => "`.`",
            Self::Question => "`?`",
            Self::Plus => "`+`",
            Self::PlusPlus => "`++`",
            Self::Minus => "`-`",
            Self::MinusMinus => "`--`",
            Self::Star => "`*`",
            Self::Slash => "`/`",
            Self::Percent => "`%`",
            Self::Bang => "`!`",
            Self::Less => "`<`",
            Self::LessEqual => "`<=`",
            Self::Greater => "`>`",
            Self::GreaterEqual => "`>=`",
            Self::EqualEqual => "`==`",
            Self::BangEqual => "`!=`",
            Self::AndAnd => "`&&`",
            Self::OrOr => "`||`",
            Self::Equal => "`=`",
            Self::PlusEqual => "`+=`",
            Self::MinusEqual => "`-=`",
            Self::StarEqual => "`*=`",
            Self::SlashEqual => "`/=`",
            Self::Eof => "end of file",
        }
    }
}
