//! Internal worker pool that runs Aster MIR functions concurrently.
//!
//! Each worker owns one [`PreparedProgram`], built once inside the worker's
//! own thread from a shared, read-only `Arc<mir::Module>`, and reuses it for
//! every task it accepts. Every task still gets a brand new
//! `aster_runtime::ExecutionContext` (see [`PreparedProgram::invoke`]), so
//! tasks never share arenas even when run back to back on the same worker.
//! No `JITModule` is ever shared between workers or moved after creation.

use std::collections::VecDeque;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Condvar, Mutex, mpsc};
use std::thread::{self, JoinHandle};

use super::completion_queue::{CompletionQueue, CompletionToken};
use super::execution::PreparedProgram;
use super::{BackendError, ExecutionValue, mir, select_entry, validate_module};

/// Internal task identity, for diagnostics only. Generated by the pool that
/// accepted the task; never reused across pools.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) struct TaskId(u64);

/// The owned result of one plain or awaited task, delivered over its own channel.
#[derive(Clone, Debug, PartialEq)]
pub(super) enum TaskOutcome {
    Completed(ExecutionValue, super::MemoryStats),
    Failed(BackendError),
}

/// The result of one `Parallel` chunk: either it ran every index cleanly, or
/// it stopped at the first failing one, reporting that iteration's logical
/// index (the actual `int` for `For`, the array position for `ForEach`).
#[derive(Debug)]
pub(super) struct ChunkOutcome {
    pub(super) first_error: Option<(i64, BackendError)>,
}

/// The result of one `Parallel.Reduce` accumulation chunk: the chunk's owned
/// partial result, or the first failing element's logical array position.
#[derive(Debug)]
pub(super) struct ReduceChunkOutcome {
    pub(super) result: Result<ExecutionValue, (i64, BackendError)>,
}

/// The result of one `Parallel.Reduce` combine step: the combined scalar, or
/// a controlled error from that specific `Combine` call. No logical index: a
/// combine step folds two chunk partials, not one array position.
#[derive(Debug)]
pub(super) struct CombineOutcome {
    pub(super) result: Result<ExecutionValue, BackendError>,
}

/// What one job asks a worker to do. Every variant resolves a MIR function by
/// its concrete symbol; no textual lookup and no per-iteration JIT happen.
pub(super) enum JobKind {
    /// One zero-parameter `Task.Run` target.
    Task {
        symbol: mir::SymbolId,
        collect_stats: bool,
    },
    /// `Body(int)` over a contiguous half-open range `[start, end)`.
    ForChunk {
        symbol: mir::SymbolId,
        start: i32,
        end: i32,
    },
    /// `Body(T)` over host-owned scalar copies, whose first element is the
    /// original array position `base`.
    ForEachChunk {
        symbol: mir::SymbolId,
        base: usize,
        values: Vec<ExecutionValue>,
    },
    /// `Accumulate(identity, values[i])` folded sequentially over one
    /// `Parallel.Reduce` chunk of host-owned scalar copies, whose first
    /// element is the original array position `base`. `identity` is an owned
    /// copy, never a shared accumulator.
    ReduceChunk {
        symbol: mir::SymbolId,
        base: usize,
        identity: ExecutionValue,
        values: Vec<ExecutionValue>,
    },
    /// One `Combine(left, right)` call submitted to the pool during a
    /// `Parallel.Reduce`'s sequential combination phase, so the host thread
    /// running `Main` never reenters its own `PreparedProgram`. Submitted one
    /// at a time, never concurrently with another combine step of the same
    /// reduction.
    CombineStep {
        symbol: mir::SymbolId,
        left: ExecutionValue,
        right: ExecutionValue,
    },
    /// Test-only host panic injection used to verify pool-wide failure cleanup.
    #[cfg(test)]
    Panic(Arc<std::sync::Barrier>),
}

/// The kind-matched reply channel for one job.
enum Respond {
    Task(mpsc::Sender<TaskOutcome>),
    Chunk(mpsc::Sender<ChunkOutcome>),
    Reduce(mpsc::Sender<ReduceChunkOutcome>),
    Combine(mpsc::Sender<CombineOutcome>),
}

struct Job {
    kind: JobKind,
    respond: Respond,
    /// Present only for an awaited async inner task; signalled after the reply
    /// is sent so the host pump wakes even if the reply channel was dropped.
    completion: Option<(Arc<CompletionQueue>, CompletionToken)>,
}

struct QueueState {
    jobs: VecDeque<Job>,
    closed: bool,
}

/// MPMC job queue built from `std` primitives only: a mutex-guarded deque
/// plus a condition variable, with an explicit closed flag instead of a
/// blocking `mpsc::Receiver`.
struct JobQueue {
    state: Mutex<QueueState>,
    not_empty: Condvar,
}

impl JobQueue {
    fn new() -> Self {
        Self {
            state: Mutex::new(QueueState {
                jobs: VecDeque::new(),
                closed: false,
            }),
            not_empty: Condvar::new(),
        }
    }

    /// Queue `job` and wake one waiting worker. Fails once the queue has
    /// been closed by [`Self::close`].
    fn push(&self, job: Job) -> Result<(), BackendError> {
        let mut state = self.state.lock().expect("job queue mutex is not poisoned");
        if state.closed {
            return Err(BackendError::new("execution pool is shut down"));
        }
        state.jobs.push_back(job);
        drop(state);
        self.not_empty.notify_one();
        Ok(())
    }

    /// Block until a job is available or the queue is closed and drained.
    /// Already-queued jobs are always returned before `None`, so a closed
    /// queue still lets every accepted job run to completion.
    fn pop(&self) -> Option<Job> {
        let mut state = self.state.lock().expect("job queue mutex is not poisoned");
        loop {
            if let Some(job) = state.jobs.pop_front() {
                return Some(job);
            }
            if state.closed {
                return None;
            }
            state = self
                .not_empty
                .wait(state)
                .expect("job queue mutex is not poisoned");
        }
    }

    /// Mark the queue closed and wake every worker so idle ones can exit.
    fn close(&self) {
        let mut state = self.state.lock().expect("job queue mutex is not poisoned");
        state.closed = true;
        drop(state);
        self.not_empty.notify_all();
    }

    /// Fail the queue after a worker panic. Dropping queued jobs disconnects
    /// their reply channels, so every already-issued handle unblocks with a
    /// controlled error instead of waiting forever for a worker that died.
    fn abort(&self) {
        let mut state = self.state.lock().expect("job queue mutex is not poisoned");
        state.closed = true;
        state.jobs.clear();
        drop(state);
        self.not_empty.notify_all();
    }
}

/// Build this worker's `PreparedProgram` and report the outcome to the pool
/// constructor over `ready` before ever touching the job queue. On failure
/// the worker reports the cause and exits without entering the job loop.
fn worker_loop(
    module: &mir::Module,
    queue: &JobQueue,
    ready: &mpsc::Sender<Result<(), BackendError>>,
) {
    let program = match PreparedProgram::prepare(module) {
        Ok(program) => program,
        Err(error) => {
            let _ = ready.send(Err(error));
            return;
        }
    };
    if ready.send(Ok(())).is_err() {
        // The pool constructor already gave up, most likely because a
        // sibling worker failed to prepare. Nothing left to serve.
        return;
    }
    while let Some(job) = queue.pop() {
        // Nested concurrency from within a job run by this worker is not
        // supported in this version: the worker's own `PreparedProgram` never
        // registers a task runtime, so `Task.Run`/`Parallel` inside a job
        // fails with a controlled error instead of deadlocking or reaching
        // this same pool recursively. The frontend also rejects it statically.
        let Job {
            kind,
            respond,
            completion,
        } = job;
        match (kind, respond) {
            (
                JobKind::Task {
                    symbol,
                    collect_stats,
                },
                Respond::Task(reply),
            ) => {
                let outcome = match program.invoke(symbol, collect_stats, None, None, None) {
                    Ok((value, stats)) => TaskOutcome::Completed(value, stats),
                    Err(error) => TaskOutcome::Failed(error),
                };
                // The receiver may already have been dropped; ignore that.
                let _ = reply.send(outcome);
            }
            (JobKind::ForChunk { symbol, start, end }, Respond::Chunk(reply)) => {
                let _ = reply.send(program.run_for_chunk(symbol, start, end));
            }
            (
                JobKind::ForEachChunk {
                    symbol,
                    base,
                    values,
                },
                Respond::Chunk(reply),
            ) => {
                let _ = reply.send(program.run_for_each_chunk(symbol, base, &values));
            }
            (
                JobKind::ReduceChunk {
                    symbol,
                    base,
                    identity,
                    values,
                },
                Respond::Reduce(reply),
            ) => {
                let _ = reply.send(program.run_reduce_chunk(symbol, base, &identity, &values));
            }
            (
                JobKind::CombineStep {
                    symbol,
                    left,
                    right,
                },
                Respond::Combine(reply),
            ) => {
                let _ = reply.send(program.run_combine_step(symbol, &left, &right));
            }
            #[cfg(test)]
            (JobKind::Panic(barrier), Respond::Task(_reply)) => {
                barrier.wait();
                panic!("simulated worker panic");
            }
            // A kind/reply mismatch is impossible: both are built together in
            // `submit`/`submit_parallel`. Nothing to report if it ever occurs.
            _ => {}
        }
        // Signal the awaited async task's completion token last, so the host
        // pump wakes even if the reply above could not be delivered.
        if let Some((queue, token)) = completion {
            queue.push(token);
        }
    }
}

/// A task in flight. Owns its own single-use result channel; no result ever
/// passes through shared or global state.
pub(super) struct TaskHandle {
    id: TaskId,
    receiver: mpsc::Receiver<TaskOutcome>,
}

impl TaskHandle {
    // Diagnostics-only accessor, currently exercised only by tests; kept for
    // the same reason `TaskId` itself exists (see its doc comment).
    #[allow(dead_code)]
    pub(super) fn id(&self) -> TaskId {
        self.id
    }

    /// Block until the task's worker responds, exactly like a normal
    /// channel receive. If the worker terminated before responding
    /// (including via an internal invariant panic, which this pool does not
    /// treat as a recoverable Aster error), this returns a controlled error
    /// instead of blocking forever or panicking.
    pub(super) fn join(self) -> Result<TaskOutcome, BackendError> {
        self.receiver.recv().map_err(|_| {
            BackendError::new(format!(
                "task {:?}'s worker disconnected before sending a result",
                self.id
            ))
        })
    }
}

/// Runs Aster MIR functions from one shared, read-only `mir::Module` across
/// a fixed set of worker threads. Not a general-purpose closure pool: every
/// job is exactly "invoke this resolved MIR function symbol."
pub(super) struct ExecutionPool {
    // Only read by `resolve`, currently exercised only by tests: today's
    // sole caller (`task_runtime::TaskRuntime`, via `execution::execute_resolved`)
    // already has its own `mir::Module` reference and resolves the entry
    // itself before the pool exists.
    #[allow(dead_code)]
    module: Arc<mir::Module>,
    queue: Arc<JobQueue>,
    // A mutex so `shutdown` can join every worker from `&self`: `submit` and
    // `shutdown` both need to be callable without consuming the pool, since
    // rejecting a post-shutdown `submit` on the same value is part of the
    // contract.
    workers: Mutex<Vec<JoinHandle<()>>>,
    next_task_id: AtomicU64,
}

impl ExecutionPool {
    /// Validate `module` once, then start `worker_count` threads, each of
    /// which builds its own `PreparedProgram` before accepting tasks.
    /// Returns only once every worker has confirmed it is ready; if any
    /// worker fails to prepare, no `Self` is ever returned.
    pub(super) fn new(module: Arc<mir::Module>, worker_count: usize) -> Result<Self, BackendError> {
        Self::new_internal(module, worker_count, None)
    }

    /// Test-only injection point: forces the worker at `failing_index` to
    /// report a simulated preparation failure instead of running
    /// `PreparedProgram::prepare`, without adding a public trait or factory.
    #[cfg(test)]
    fn new_with_failing_worker(
        module: Arc<mir::Module>,
        worker_count: usize,
        failing_index: usize,
    ) -> Result<Self, BackendError> {
        Self::new_internal(module, worker_count, Some(failing_index))
    }

    fn new_internal(
        module: Arc<mir::Module>,
        worker_count: usize,
        failing_index: Option<usize>,
    ) -> Result<Self, BackendError> {
        if worker_count == 0 {
            return Err(BackendError::new(
                "execution pool requires at least one worker",
            ));
        }
        validate_module(&module)?;

        let queue = Arc::new(JobQueue::new());
        let mut workers = Vec::with_capacity(worker_count);
        let mut ready_receivers = Vec::with_capacity(worker_count);
        for index in 0..worker_count {
            let worker_module = Arc::clone(&module);
            let worker_queue = Arc::clone(&queue);
            let panic_queue = Arc::clone(&queue);
            let (ready_tx, ready_rx) = mpsc::channel();
            let simulate_this_worker_failing = failing_index == Some(index);
            workers.push(thread::spawn(move || {
                let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    if simulate_this_worker_failing {
                        let _ = ready_tx.send(Err(BackendError::new(
                            "simulated worker preparation failure",
                        )));
                        return;
                    }
                    worker_loop(&worker_module, &worker_queue, &ready_tx);
                }));
                if outcome.is_err() {
                    panic_queue.abort();
                }
            }));
            ready_receivers.push(ready_rx);
        }

        // Wait for every worker to confirm readiness before this pool can be
        // used, so `submit` never races a worker that has not built its
        // `PreparedProgram` yet.
        let mut failure: Option<BackendError> = None;
        for ready_rx in ready_receivers {
            let outcome = ready_rx.recv().unwrap_or_else(|_| {
                Err(BackendError::new(
                    "a worker thread terminated before completing initialization",
                ))
            });
            if let Err(error) = outcome {
                if failure.is_none() {
                    failure = Some(error);
                }
            }
        }

        if let Some(error) = failure {
            queue.close();
            for worker in workers {
                let _ = worker.join();
            }
            return Err(error);
        }

        Ok(Self {
            module,
            queue,
            workers: Mutex::new(workers),
            next_task_id: AtomicU64::new(0),
        })
    }

    /// Resolve a public, zero-parameter, scalar-returning function by name
    /// to the `mir::SymbolId` [`Self::submit`] expects. Does the one textual
    /// lookup this pool ever performs; workers never look functions up by
    /// name. Currently exercised only by tests: `task_runtime::TaskRuntime`
    /// resolves `Task.Run`'s target from an already-compiled `SymbolId`
    /// baked in by codegen, never by name, but this stays available for a
    /// future direct pool caller that only has a name.
    #[allow(dead_code)]
    pub(super) fn resolve(&self, function_name: &str) -> Result<mir::SymbolId, BackendError> {
        select_entry(&self.module, function_name).map(|function| function.symbol)
    }

    /// Queue one plain or awaited `Task.Run` job that invokes `symbol` on the
    /// next free worker with its own fresh `ExecutionContext`. `completion`,
    /// present only for an awaited async inner, is signalled after the reply.
    /// Fails if the pool has been shut down.
    pub(super) fn submit(
        &self,
        symbol: mir::SymbolId,
        collect_stats: bool,
        completion: Option<(Arc<CompletionQueue>, CompletionToken)>,
    ) -> Result<TaskHandle, BackendError> {
        let id = TaskId(self.next_task_id.fetch_add(1, Ordering::Relaxed));
        let (reply, receiver) = mpsc::channel();
        self.queue.push(Job {
            kind: JobKind::Task {
                symbol,
                collect_stats,
            },
            respond: Respond::Task(reply),
            completion,
        })?;
        Ok(TaskHandle { id, receiver })
    }

    /// Queue one `Parallel` chunk and return the channel its [`ChunkOutcome`]
    /// arrives on. Parallel chunks never carry a completion token.
    pub(super) fn submit_parallel(
        &self,
        kind: JobKind,
    ) -> Result<mpsc::Receiver<ChunkOutcome>, BackendError> {
        let (reply, receiver) = mpsc::channel();
        self.queue.push(Job {
            kind,
            respond: Respond::Chunk(reply),
            completion: None,
        })?;
        Ok(receiver)
    }

    /// Queue one `Parallel.Reduce` accumulation chunk and return the channel
    /// its [`ReduceChunkOutcome`] arrives on.
    pub(super) fn submit_reduce_chunk(
        &self,
        kind: JobKind,
    ) -> Result<mpsc::Receiver<ReduceChunkOutcome>, BackendError> {
        let (reply, receiver) = mpsc::channel();
        self.queue.push(Job {
            kind,
            respond: Respond::Reduce(reply),
            completion: None,
        })?;
        Ok(receiver)
    }

    /// Queue one `Parallel.Reduce` combine step and return the channel its
    /// [`CombineOutcome`] arrives on. Callers submit these one at a time,
    /// waiting for each result before submitting the next, so the sequential
    /// combination phase never runs two `Combine` calls of the same
    /// reduction concurrently.
    pub(super) fn submit_combine_step(
        &self,
        kind: JobKind,
    ) -> Result<mpsc::Receiver<CombineOutcome>, BackendError> {
        let (reply, receiver) = mpsc::channel();
        self.queue.push(Job {
            kind,
            respond: Respond::Combine(reply),
            completion: None,
        })?;
        Ok(receiver)
    }

    #[cfg(test)]
    fn submit_panicking(
        &self,
        barrier: Arc<std::sync::Barrier>,
    ) -> Result<TaskHandle, BackendError> {
        let id = TaskId(self.next_task_id.fetch_add(1, Ordering::Relaxed));
        let (reply, receiver) = mpsc::channel();
        self.queue.push(Job {
            kind: JobKind::Panic(barrier),
            respond: Respond::Task(reply),
            completion: None,
        })?;
        Ok(TaskHandle { id, receiver })
    }

    /// Stop accepting new tasks, let every already-accepted task finish, and
    /// wait for every worker thread to exit. Idempotent: calling it again,
    /// or dropping the pool afterward, joins an already-empty worker list.
    /// A `submit` call after this returns fails.
    pub(super) fn shutdown(&self) {
        self.queue.close();
        let mut workers = self.workers.lock().expect("workers mutex is not poisoned");
        for worker in workers.drain(..) {
            let _ = worker.join();
        }
    }
}

impl Drop for ExecutionPool {
    fn drop(&mut self) {
        self.shutdown();
    }
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use super::*;

    const TEST_TIMEOUT: Duration = Duration::from_secs(5);

    fn compile(source: &str) -> mir::Module {
        aster_compiler::compile(source)
            .expect("source compiles")
            .mir
    }

    /// Calls the real (blocking) `TaskHandle::join` on a helper thread and
    /// bounds the wait from here, so a stuck worker fails the test instead
    /// of hanging it. Callers use this only where a clean completion is
    /// expected; a channel-level failure here is itself a test bug.
    fn join_with_timeout(handle: TaskHandle) -> TaskOutcome {
        let id = handle.id();
        let (sender, receiver) = mpsc::channel();
        thread::spawn(move || {
            let _ = sender.send(handle.join());
        });
        receiver
            .recv_timeout(TEST_TIMEOUT)
            .unwrap_or_else(|_| panic!("task {id:?} did not respond before the test timeout"))
            .unwrap_or_else(|error| panic!("task {id:?} channel failed: {error}"))
    }

    /// `JobKind` (what a worker actually receives) must stay `Send + 'static`
    /// with no raw pointer, `ExecutionContext`, or `PreparedProgram` inside
    /// it. This is a compile-time guarantee, not a runtime assertion: a
    /// future variant carrying `*mut aster_runtime::ExecutionContext` or a
    /// borrowed array pointer would make `JobKind` stop being `Send` (raw
    /// pointers are not `Send`) and this test would fail to *compile*, not
    /// just fail to pass. `ExecutionValue` (the only thing `ForEachChunk`
    /// carries per element) is scalar-only, never a class/array/interface
    /// handle (see `values::primitive`).
    #[test]
    fn job_kind_carries_only_owned_send_data_no_arena_pointer_or_context() {
        fn assert_send<T: Send>() {}
        assert_send::<JobKind>();
        assert_send::<ChunkOutcome>();
        assert_send::<TaskOutcome>();
        assert_send::<Vec<ExecutionValue>>();
        // `Parallel.Reduce`'s job/outcome types must hold to the same
        // guarantee: only owned scalars, never a pointer or `ExecutionContext`.
        assert_send::<ReduceChunkOutcome>();
        assert_send::<CombineOutcome>();
    }

    #[test]
    fn single_worker_pool_runs_a_task() {
        let module = Arc::new(compile("public int Run() { return 40 + 2; }"));
        let pool = ExecutionPool::new(module, 1).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let handle = pool.submit(run, false, None).expect("task is accepted");
        match join_with_timeout(handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(42)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn multiple_workers_run_many_tasks_of_the_same_function() {
        let module = Arc::new(compile("public int Run() { return 40 + 2; }"));
        let pool = ExecutionPool::new(module, 4).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let handles: Vec<_> = (0..20)
            .map(|_| pool.submit(run, false, None).expect("task is accepted"))
            .collect();

        for handle in handles {
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(42)),
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn workers_run_different_functions_of_the_same_module_regardless_of_completion_order() {
        let module = Arc::new(compile(
            "public int Answer() { return 42; } public int Double(int value) { return value * 2; } public int Run() { return Double(Answer()); }",
        ));
        let pool = ExecutionPool::new(module, 3).expect("pool starts");
        let answer = pool.resolve("Answer").expect("Answer resolves");
        let run = pool.resolve("Run").expect("Run resolves");

        // Submitted out of the order results are asserted in, so a pass
        // proves results are matched to their own task, not to arrival order.
        let run_handle = pool.submit(run, false, None).expect("task is accepted");
        let answer_handle = pool.submit(answer, false, None).expect("task is accepted");

        match join_with_timeout(answer_handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(42)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }
        match join_with_timeout(run_handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(84)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn each_task_gets_independent_non_accumulating_metrics() {
        let module = Arc::new(compile(
            "public int Run() { int[] values = [20, 22]; return values[0] + values[1]; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let handles: Vec<_> = (0..6)
            .map(|_| pool.submit(run, true, None).expect("task is accepted"))
            .collect();

        for handle in handles {
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, stats) => {
                    assert_eq!(value, ExecutionValue::Int(42));
                    assert_eq!(stats.total_allocations, 1);
                    assert_eq!(stats.array_allocations, 1);
                    // No persistent leftover from any other task's arena and
                    // the temporary array is fully rewound before return.
                    assert_eq!(stats.used_bytes, 0);
                }
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn a_controlled_error_in_one_task_does_not_block_later_tasks() {
        let module = Arc::new(compile(
            "public int Failing() { int[] values = new int[1]; return values[5]; } public int Ok() { return 1; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let failing = pool.resolve("Failing").expect("Failing resolves");
        let ok = pool.resolve("Ok").expect("Ok resolves");

        let failing_handle = pool.submit(failing, false, None).expect("task is accepted");
        let ok_handle = pool.submit(ok, false, None).expect("task is accepted");

        match join_with_timeout(failing_handle) {
            TaskOutcome::Failed(error) => assert!(error.message().contains("array index 5")),
            TaskOutcome::Completed(..) => panic!("expected a controlled runtime error"),
        }
        match join_with_timeout(ok_handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(1)),
            TaskOutcome::Failed(error) => panic!("unaffected task failed: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn shutdown_still_runs_every_already_accepted_job() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let handles: Vec<_> = (0..10)
            .map(|_| pool.submit(run, false, None).expect("task is accepted"))
            .collect();

        // Nothing has been joined yet: every job is still only queued or
        // in flight when shutdown begins draining the queue.
        pool.shutdown();

        for handle in handles {
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(1)),
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }
    }

    #[test]
    fn submitting_after_shutdown_fails() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 1).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        pool.shutdown();

        let result = pool.submit(run, false, None);
        assert!(result.is_err());
    }

    #[test]
    fn many_temporary_tasks_across_multiple_workers_all_end_with_zero_used_bytes() {
        let module = Arc::new(compile(
            "public int Run() { int[] values = [20, 22]; return values[0] + values[1]; }",
        ));
        let pool = ExecutionPool::new(module, 4).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let handles: Vec<_> = (0..24)
            .map(|_| pool.submit(run, true, None).expect("task is accepted"))
            .collect();

        for handle in handles {
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, stats) => {
                    assert_eq!(value, ExecutionValue::Int(42));
                    assert_eq!(stats.used_bytes, 0);
                }
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn many_persistent_tasks_on_one_worker_do_not_accumulate_memory() {
        let module = Arc::new(compile(
            "public interface IBox { int Get(); } public class Box : IBox { public int value; public int Get() { return value; } } public int Run() { Box box = new Box(); box.value = 1; IBox view = box; return view.Get(); }",
        ));
        // A single worker serializes every task, so this is the strictest
        // check that persistent storage from one task never leaks into the
        // next one on the same thread.
        let pool = ExecutionPool::new(module, 1).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let mut expected_used_bytes = None;
        for _ in 0..15 {
            let handle = pool.submit(run, true, None).expect("task is accepted");
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, stats) => {
                    assert_eq!(value, ExecutionValue::Int(1));
                    assert!(stats.used_bytes > 0);
                    let expected = *expected_used_bytes.get_or_insert(stats.used_bytes);
                    assert_eq!(stats.used_bytes, expected);
                }
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn interleaved_temporary_and_persistent_tasks_keep_independent_stats() {
        let module = Arc::new(compile(
            "public interface IBox { int Get(); } public class Box : IBox { public int value; public int Get() { return value; } } public int Persistent() { Box box = new Box(); box.value = 1; IBox view = box; return view.Get(); } public int Temporary() { int[] values = [20, 22]; return values[0] + values[1]; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let persistent = pool.resolve("Persistent").expect("Persistent resolves");
        let temporary = pool.resolve("Temporary").expect("Temporary resolves");

        for round in 0..8 {
            let symbol = if round % 2 == 0 {
                persistent
            } else {
                temporary
            };
            let handle = pool.submit(symbol, true, None).expect("task is accepted");
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, stats) => {
                    if round % 2 == 0 {
                        assert_eq!(value, ExecutionValue::Int(1));
                        assert!(stats.used_bytes > 0);
                    } else {
                        assert_eq!(value, ExecutionValue::Int(42));
                        assert_eq!(stats.used_bytes, 0);
                    }
                }
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn a_controlled_error_between_two_valid_tasks_does_not_affect_either() {
        let module = Arc::new(compile(
            "public int Ok() { return 7; } public int Failing() { int[] values = new int[1]; return values[5]; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let ok = pool.resolve("Ok").expect("Ok resolves");
        let failing = pool.resolve("Failing").expect("Failing resolves");

        let first = pool.submit(ok, false, None).expect("task is accepted");
        let middle = pool.submit(failing, false, None).expect("task is accepted");
        let last = pool.submit(ok, false, None).expect("task is accepted");

        match join_with_timeout(first) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(7)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }
        match join_with_timeout(middle) {
            TaskOutcome::Failed(error) => assert!(error.message().contains("array index 5")),
            TaskOutcome::Completed(..) => panic!("expected a controlled runtime error"),
        }
        match join_with_timeout(last) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(7)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn dropping_one_tasks_outcome_does_not_affect_another() {
        let module = Arc::new(compile(
            "public int First() { return 11; } public int Second() { return 22; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let first_symbol = pool.resolve("First").expect("First resolves");
        let second_symbol = pool.resolve("Second").expect("Second resolves");

        let first_handle = pool
            .submit(first_symbol, false, None)
            .expect("task is accepted");
        let second_handle = pool
            .submit(second_symbol, false, None)
            .expect("task is accepted");

        let first_outcome = join_with_timeout(first_handle);
        drop(first_outcome);

        match join_with_timeout(second_handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(22)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn multiple_independent_pools_do_not_interfere() {
        let module_a = Arc::new(compile("public int Run() { return 1; }"));
        let module_b = Arc::new(compile("public int Run() { return 2; }"));

        let pool_a = ExecutionPool::new(module_a, 1).expect("pool a starts");
        let pool_b = ExecutionPool::new(module_b, 1).expect("pool b starts");
        let run_a = pool_a.resolve("Run").expect("Run resolves in a");
        let run_b = pool_b.resolve("Run").expect("Run resolves in b");

        let handle_a = pool_a.submit(run_a, false, None).expect("task is accepted");
        let handle_b = pool_b.submit(run_b, false, None).expect("task is accepted");

        match join_with_timeout(handle_a) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(1)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        // Shutting down one pool must not disturb the other.
        pool_a.shutdown();

        match join_with_timeout(handle_b) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(2)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool_b.shutdown();
    }

    #[test]
    fn shutdown_with_an_empty_queue_terminates_cleanly() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 3).expect("pool starts");

        pool.shutdown();

        assert!(
            pool.submit(pool.resolve("Run").expect("Run resolves"), false, None)
                .is_err()
        );
    }

    #[test]
    fn shutdown_is_idempotent_and_drop_does_not_rejoin_workers() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");

        pool.shutdown();
        // Calling it again must not try to join an already-joined
        // `JoinHandle`, and the pool's own `Drop` will call it once more.
        pool.shutdown();

        let run = pool.resolve("Run").expect("Run resolves");
        assert!(pool.submit(run, false, None).is_err());
    }

    #[test]
    fn worker_initialization_failure_returns_a_controlled_error_without_a_partial_pool() {
        let module = Arc::new(compile("public int Run() { return 1; }"));

        let result = ExecutionPool::new_with_failing_worker(module, 3, 1);

        match result {
            Err(error) => assert!(error.message().contains("simulated worker preparation")),
            Ok(_) => panic!("a failed worker must fail the whole pool"),
        }
    }

    #[test]
    fn join_returns_a_controlled_error_when_the_response_channel_disconnects() {
        let (sender, receiver) = mpsc::channel::<TaskOutcome>();
        let handle = TaskHandle {
            id: TaskId(0),
            receiver,
        };
        drop(sender);

        let result = handle.join();
        assert!(result.is_err());
    }

    #[test]
    fn worker_panic_disconnects_queued_jobs_and_closes_the_pool() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 1).expect("pool starts");
        let barrier = Arc::new(std::sync::Barrier::new(2));
        let panicking = pool
            .submit_panicking(Arc::clone(&barrier))
            .expect("panic job is accepted");
        let queued = pool
            .submit(pool.resolve("Run").expect("Run resolves"), false, None)
            .expect("second job is queued before the panic");

        barrier.wait();

        assert!(panicking.join().is_err());
        assert!(queued.join().is_err());
        assert!(
            pool.submit(pool.resolve("Run").expect("Run resolves"), false, None)
                .is_err()
        );
    }

    #[test]
    fn transported_types_are_thread_transferable() {
        fn assert_send<T: Send>() {}
        fn assert_send_sync<T: Send + Sync>() {}

        assert_send_sync::<mir::Module>();
        assert_send::<TaskOutcome>();
        assert_send::<BackendError>();
        assert_send::<crate::MemoryStats>();
        assert_send::<Result<TaskOutcome, BackendError>>();
        // `JobKind::ForEachChunk` carries only owned `ExecutionValue` scalars,
        // never a pointer into any host arena or `ExecutionContext`: this is
        // the structural guarantee behind "no array pointer ever reaches a
        // worker" (see `async_abi::copy_scalar_array`), checked at the type
        // level rather than by inspecting job contents at runtime.
        assert_send::<JobKind>();
        assert_send::<ChunkOutcome>();
    }

    #[test]
    fn for_each_chunk_owns_its_scalar_values_not_a_pointer() {
        let chunk = JobKind::ForEachChunk {
            symbol: mir::SymbolId(0),
            base: 0,
            values: vec![crate::ExecutionValue::Int(1), crate::ExecutionValue::Int(2)],
        };
        let JobKind::ForEachChunk { values, .. } = chunk else {
            unreachable!()
        };
        // `values` is a plain, independently owned `Vec`: moving the whole
        // `JobKind` (as every job is, into the worker's queue) moves this
        // storage with it, never a reference into the submitting thread's data.
        assert_eq!(
            values,
            vec![crate::ExecutionValue::Int(1), crate::ExecutionValue::Int(2)]
        );
    }
}
