//! Internal worker pool that runs Aster MIR functions concurrently.
//!
//! Each worker owns one [`PreparedProgram`], built once inside the worker's
//! own thread from a shared, read-only `Arc<mir::Module>`, and reuses it for
//! every task it accepts. Every task still gets a brand new
//! `aster_runtime::ExecutionContext` (see [`PreparedProgram::invoke`]), so
//! tasks never share arenas even when run back to back on the same worker.
//! No `JITModule` is ever shared between workers or moved after creation.

use std::collections::VecDeque;
use std::sync::atomic::{AtomicU64, AtomicUsize, Ordering};
use std::sync::{Arc, Condvar, Mutex, mpsc};
use std::thread::{self, JoinHandle};

use super::completion_queue::{CompletionQueue, CompletionToken};
use super::execution::PreparedProgram;
use super::{BackendError, ExecutionValue, mir, select_entry, validate_module};

/// Internal task identity, for diagnostics only. Generated by the pool that
/// accepted the task; never reused across pools.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) struct TaskId(u64);

/// The owned result of one plain or awaited task, delivered over its own channel.
#[derive(Clone, Debug, PartialEq)]
pub(super) enum TaskOutcome {
    Completed(ExecutionValue, super::MemoryStats),
    Failed(BackendError),
}

/// The result of one `Parallel` chunk: either it ran every index cleanly, or
/// it stopped at the first failing one, reporting that iteration's logical
/// index (the actual `int` for `For`, the array position for `ForEach`).
#[derive(Debug)]
pub(super) struct ChunkOutcome {
    pub(super) first_error: Option<(i64, BackendError)>,
    #[cfg(feature = "aarm-telemetry")]
    pub(super) telemetry: Option<aster_runtime::AarmMemoryTelemetry>,
}

/// The result of one `Parallel.Reduce` accumulation chunk: the chunk's owned
/// partial result, or the first failing element's logical array position.
#[derive(Debug)]
pub(super) struct ReduceChunkOutcome {
    pub(super) result: Result<ExecutionValue, (i64, BackendError)>,
    #[cfg(feature = "aarm-telemetry")]
    pub(super) telemetry: Option<aster_runtime::AarmMemoryTelemetry>,
}

/// The result of one `Parallel.Reduce` combine step: the combined scalar, or
/// a controlled error from that specific `Combine` call. No logical index: a
/// combine step folds two chunk partials, not one array position.
#[derive(Debug)]
pub(super) struct CombineOutcome {
    pub(super) result: Result<ExecutionValue, BackendError>,
    #[cfg(feature = "aarm-telemetry")]
    pub(super) telemetry: Option<aster_runtime::AarmMemoryTelemetry>,
}

/// A deterministic retained-capacity entitlement carried by one logical
/// Parallel chunk. It is not charged until that chunk creates real pages.
#[derive(Clone)]
pub(super) struct ParallelMemoryBudget {
    pub(super) governor: Arc<aster_runtime::MemoryGovernor>,
    pub(super) local_limit_bytes: usize,
}

/// One frozen execution-owned memory domain shared by governed plain
/// `Task.Run` jobs. The local byte ceiling is uniform; the condition variable
/// limits how many task contexts may own that entitlement concurrently.
pub(super) struct TaskMemoryDomain {
    governor: Arc<aster_runtime::MemoryGovernor>,
    local_limit_bytes: usize,
    concurrency_limit: usize,
    active_contexts: Mutex<usize>,
    slot_available: Condvar,
    submissions: AtomicU64,
    contexts_started: AtomicU64,
    contexts_completed: AtomicU64,
    memory_failures: AtomicU64,
    active_page_fast_path_allocations: AtomicU64,
    fresh_page_allocations: AtomicU64,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[cfg(feature = "aarm-telemetry")]
pub(super) struct TaskMemoryDomainCounters {
    pub(super) submissions: u64,
    pub(super) contexts_started: u64,
    pub(super) contexts_completed: u64,
    pub(super) memory_failures: u64,
    pub(super) active_page_fast_path_allocations: u64,
    pub(super) fresh_page_allocations: u64,
}

impl TaskMemoryDomain {
    pub(super) fn new(
        governor: Arc<aster_runtime::MemoryGovernor>,
        local_limit_bytes: usize,
        concurrency_limit: usize,
    ) -> Self {
        assert!(
            concurrency_limit > 0,
            "task memory concurrency must be nonzero"
        );
        Self {
            governor,
            local_limit_bytes,
            concurrency_limit,
            active_contexts: Mutex::new(0),
            slot_available: Condvar::new(),
            submissions: AtomicU64::new(0),
            contexts_started: AtomicU64::new(0),
            contexts_completed: AtomicU64::new(0),
            memory_failures: AtomicU64::new(0),
            active_page_fast_path_allocations: AtomicU64::new(0),
            fresh_page_allocations: AtomicU64::new(0),
        }
    }

    pub(super) fn governor(&self) -> &Arc<aster_runtime::MemoryGovernor> {
        &self.governor
    }

    pub(super) fn local_limit_bytes(&self) -> usize {
        self.local_limit_bytes
    }

    pub(super) fn concurrency_limit(&self) -> usize {
        self.concurrency_limit
    }

    fn record_submission(&self) {
        self.submissions.fetch_add(1, Ordering::Relaxed);
    }

    fn acquire(self: &Arc<Self>) -> TaskMemoryPermit {
        let mut active = self
            .active_contexts
            .lock()
            .expect("task memory-domain mutex is not poisoned");
        while *active >= self.concurrency_limit {
            active = self
                .slot_available
                .wait(active)
                .expect("task memory-domain mutex is not poisoned");
        }
        *active += 1;
        self.contexts_started.fetch_add(1, Ordering::Relaxed);
        TaskMemoryPermit {
            domain: Arc::clone(self),
        }
    }

    fn record_outcome(
        &self,
        outcome: &TaskOutcome,
        telemetry: Option<&aster_runtime::AarmMemoryTelemetry>,
    ) {
        if matches!(outcome, TaskOutcome::Failed(error) if error.message().contains("deterministic Task.Run memory entitlement"))
        {
            self.memory_failures.fetch_add(1, Ordering::Relaxed);
        }
        if let Some(telemetry) = telemetry {
            self.active_page_fast_path_allocations.fetch_add(
                telemetry.total.events.active_page_fast_path_allocations,
                Ordering::Relaxed,
            );
            self.fresh_page_allocations.fetch_add(
                telemetry.total.events.fresh_regular_page_allocations
                    + telemetry.total.events.fresh_oversized_page_allocations,
                Ordering::Relaxed,
            );
        }
    }

    #[cfg(feature = "aarm-telemetry")]
    pub(super) fn counters(&self) -> TaskMemoryDomainCounters {
        TaskMemoryDomainCounters {
            submissions: self.submissions.load(Ordering::Relaxed),
            contexts_started: self.contexts_started.load(Ordering::Relaxed),
            contexts_completed: self.contexts_completed.load(Ordering::Relaxed),
            memory_failures: self.memory_failures.load(Ordering::Relaxed),
            active_page_fast_path_allocations: self
                .active_page_fast_path_allocations
                .load(Ordering::Relaxed),
            fresh_page_allocations: self.fresh_page_allocations.load(Ordering::Relaxed),
        }
    }
}

struct TaskMemoryPermit {
    domain: Arc<TaskMemoryDomain>,
}

/// One frozen execution-owned memory domain shared by host `MoveNext` steps
/// and their awaited worker jobs. Entitlements are fixed byte ceilings; only
/// real arena pages are charged to the shared governor.
pub(super) struct AsyncMemoryDomain {
    governor: Arc<aster_runtime::MemoryGovernor>,
    move_next_limit_bytes: usize,
    inner_limit_bytes: usize,
    move_next_contexts_started: AtomicU64,
    move_next_contexts_completed: AtomicU64,
    inner_contexts_started: AtomicU64,
    inner_contexts_completed: AtomicU64,
    move_next_memory_failures: AtomicU64,
    inner_memory_failures: AtomicU64,
    move_next_fast_path_allocations: AtomicU64,
    move_next_fresh_page_allocations: AtomicU64,
    inner_fast_path_allocations: AtomicU64,
    inner_fresh_page_allocations: AtomicU64,
    live_contexts: AtomicUsize,
    peak_live_contexts: AtomicUsize,
}

#[derive(Clone, Copy)]
enum AsyncContextRole {
    MoveNext,
    Inner,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[cfg(feature = "aarm-telemetry")]
pub(super) struct AsyncMemoryDomainCounters {
    pub(super) move_next_contexts_started: u64,
    pub(super) move_next_contexts_completed: u64,
    pub(super) inner_contexts_started: u64,
    pub(super) inner_contexts_completed: u64,
    pub(super) move_next_memory_failures: u64,
    pub(super) inner_memory_failures: u64,
    pub(super) move_next_fast_path_allocations: u64,
    pub(super) move_next_fresh_page_allocations: u64,
    pub(super) inner_fast_path_allocations: u64,
    pub(super) inner_fresh_page_allocations: u64,
    pub(super) peak_live_contexts: usize,
}

impl AsyncMemoryDomain {
    pub(super) fn new(
        governor: Arc<aster_runtime::MemoryGovernor>,
        move_next_limit_bytes: usize,
        inner_limit_bytes: usize,
    ) -> Self {
        Self {
            governor,
            move_next_limit_bytes,
            inner_limit_bytes,
            move_next_contexts_started: AtomicU64::new(0),
            move_next_contexts_completed: AtomicU64::new(0),
            inner_contexts_started: AtomicU64::new(0),
            inner_contexts_completed: AtomicU64::new(0),
            move_next_memory_failures: AtomicU64::new(0),
            inner_memory_failures: AtomicU64::new(0),
            move_next_fast_path_allocations: AtomicU64::new(0),
            move_next_fresh_page_allocations: AtomicU64::new(0),
            inner_fast_path_allocations: AtomicU64::new(0),
            inner_fresh_page_allocations: AtomicU64::new(0),
            live_contexts: AtomicUsize::new(0),
            peak_live_contexts: AtomicUsize::new(0),
        }
    }

    pub(super) fn governor(&self) -> &Arc<aster_runtime::MemoryGovernor> {
        &self.governor
    }

    pub(super) fn move_next_limit_bytes(&self) -> usize {
        self.move_next_limit_bytes
    }

    pub(super) fn inner_limit_bytes(&self) -> usize {
        self.inner_limit_bytes
    }

    pub(super) fn acquire_move_next(self: &Arc<Self>) -> AsyncMemoryPermit {
        self.acquire(AsyncContextRole::MoveNext)
    }

    fn acquire_inner(self: &Arc<Self>) -> AsyncMemoryPermit {
        self.acquire(AsyncContextRole::Inner)
    }

    fn acquire(self: &Arc<Self>, role: AsyncContextRole) -> AsyncMemoryPermit {
        match role {
            AsyncContextRole::MoveNext => {
                self.move_next_contexts_started
                    .fetch_add(1, Ordering::Relaxed);
            }
            AsyncContextRole::Inner => {
                self.inner_contexts_started.fetch_add(1, Ordering::Relaxed);
            }
        }
        let live = self.live_contexts.fetch_add(1, Ordering::Relaxed) + 1;
        self.peak_live_contexts.fetch_max(live, Ordering::Relaxed);
        AsyncMemoryPermit {
            domain: Arc::clone(self),
            role,
        }
    }

    pub(super) fn record_move_next_outcome(
        &self,
        outcome: &Result<(ExecutionValue, super::MemoryStats), BackendError>,
        telemetry: Option<&aster_runtime::AarmMemoryTelemetry>,
    ) {
        if matches!(outcome, Err(error) if error.message().contains("deterministic async MoveNext memory entitlement"))
        {
            self.move_next_memory_failures
                .fetch_add(1, Ordering::Relaxed);
        }
        self.record_allocator_events(AsyncContextRole::MoveNext, telemetry);
    }

    fn record_inner_outcome(
        &self,
        outcome: &TaskOutcome,
        telemetry: Option<&aster_runtime::AarmMemoryTelemetry>,
    ) {
        if matches!(outcome, TaskOutcome::Failed(error) if error.message().contains("deterministic async awaited-inner memory entitlement"))
        {
            self.inner_memory_failures.fetch_add(1, Ordering::Relaxed);
        }
        self.record_allocator_events(AsyncContextRole::Inner, telemetry);
    }

    fn record_allocator_events(
        &self,
        role: AsyncContextRole,
        telemetry: Option<&aster_runtime::AarmMemoryTelemetry>,
    ) {
        let Some(telemetry) = telemetry else { return };
        let fast = telemetry.total.events.active_page_fast_path_allocations;
        let fresh = telemetry.total.events.fresh_regular_page_allocations
            + telemetry.total.events.fresh_oversized_page_allocations;
        match role {
            AsyncContextRole::MoveNext => {
                self.move_next_fast_path_allocations
                    .fetch_add(fast, Ordering::Relaxed);
                self.move_next_fresh_page_allocations
                    .fetch_add(fresh, Ordering::Relaxed);
            }
            AsyncContextRole::Inner => {
                self.inner_fast_path_allocations
                    .fetch_add(fast, Ordering::Relaxed);
                self.inner_fresh_page_allocations
                    .fetch_add(fresh, Ordering::Relaxed);
            }
        }
    }

    #[cfg(feature = "aarm-telemetry")]
    pub(super) fn counters(&self) -> AsyncMemoryDomainCounters {
        AsyncMemoryDomainCounters {
            move_next_contexts_started: self.move_next_contexts_started.load(Ordering::Relaxed),
            move_next_contexts_completed: self.move_next_contexts_completed.load(Ordering::Relaxed),
            inner_contexts_started: self.inner_contexts_started.load(Ordering::Relaxed),
            inner_contexts_completed: self.inner_contexts_completed.load(Ordering::Relaxed),
            move_next_memory_failures: self.move_next_memory_failures.load(Ordering::Relaxed),
            inner_memory_failures: self.inner_memory_failures.load(Ordering::Relaxed),
            move_next_fast_path_allocations: self
                .move_next_fast_path_allocations
                .load(Ordering::Relaxed),
            move_next_fresh_page_allocations: self
                .move_next_fresh_page_allocations
                .load(Ordering::Relaxed),
            inner_fast_path_allocations: self.inner_fast_path_allocations.load(Ordering::Relaxed),
            inner_fresh_page_allocations: self.inner_fresh_page_allocations.load(Ordering::Relaxed),
            peak_live_contexts: self.peak_live_contexts.load(Ordering::Relaxed),
        }
    }
}

pub(super) struct AsyncMemoryPermit {
    domain: Arc<AsyncMemoryDomain>,
    role: AsyncContextRole,
}

impl Drop for AsyncMemoryPermit {
    fn drop(&mut self) {
        self.domain.live_contexts.fetch_sub(1, Ordering::Relaxed);
        match self.role {
            AsyncContextRole::MoveNext => {
                self.domain
                    .move_next_contexts_completed
                    .fetch_add(1, Ordering::Relaxed);
            }
            AsyncContextRole::Inner => {
                self.domain
                    .inner_contexts_completed
                    .fetch_add(1, Ordering::Relaxed);
            }
        }
    }
}

pub(super) enum TaskMemoryPolicy {
    Plain(Arc<TaskMemoryDomain>),
    AsyncInner(Arc<AsyncMemoryDomain>),
}

impl TaskMemoryPolicy {
    pub(super) fn context(&self) -> aster_runtime::ExecutionContext {
        match self {
            Self::Plain(domain) => aster_runtime::ExecutionContext::with_task_memory_budget(
                Arc::clone(domain.governor()),
                domain.local_limit_bytes(),
            ),
            Self::AsyncInner(domain) => {
                aster_runtime::ExecutionContext::with_async_inner_memory_budget(
                    Arc::clone(domain.governor()),
                    domain.inner_limit_bytes(),
                )
            }
        }
    }
}

impl Drop for TaskMemoryPermit {
    fn drop(&mut self) {
        let mut active = self
            .domain
            .active_contexts
            .lock()
            .expect("task memory-domain mutex is not poisoned");
        *active = active
            .checked_sub(1)
            .expect("task memory-domain active count underflow");
        self.domain
            .contexts_completed
            .fetch_add(1, Ordering::Relaxed);
        drop(active);
        self.domain.slot_available.notify_one();
    }
}

/// What one job asks a worker to do. Every variant resolves a MIR function by
/// its concrete symbol; no textual lookup and no per-iteration JIT happen.
pub(super) enum JobKind {
    /// One zero-parameter `Task.Run` target.
    Task {
        symbol: mir::SymbolId,
        collect_stats: bool,
        memory_policy: Option<TaskMemoryPolicy>,
    },
    /// `Body(int)` over a contiguous half-open range `[start, end)`.
    ForChunk {
        symbol: mir::SymbolId,
        start: i32,
        end: i32,
        memory_budget: Option<ParallelMemoryBudget>,
    },
    /// `Body(T)` over host-owned scalar copies, whose first element is the
    /// original array position `base`.
    ForEachChunk {
        symbol: mir::SymbolId,
        base: usize,
        values: Arc<Vec<ExecutionValue>>,
        range: std::ops::Range<usize>,
        memory_budget: Option<ParallelMemoryBudget>,
    },
    /// `Accumulate(identity, values[i])` folded sequentially over one
    /// `Parallel.Reduce` chunk of host-owned scalar copies, whose first
    /// element is the original array position `base`. `identity` is an owned
    /// copy, never a shared accumulator.
    ReduceChunk {
        symbol: mir::SymbolId,
        base: usize,
        identity: ExecutionValue,
        values: Arc<Vec<ExecutionValue>>,
        range: std::ops::Range<usize>,
        memory_budget: Option<ParallelMemoryBudget>,
    },
    /// One `Combine(left, right)` call submitted to the pool during a
    /// `Parallel.Reduce`'s sequential combination phase, so the host thread
    /// running `Main` never reenters its own `PreparedProgram`. Submitted one
    /// at a time, never concurrently with another combine step of the same
    /// reduction.
    CombineStep {
        symbol: mir::SymbolId,
        left: ExecutionValue,
        right: ExecutionValue,
        memory_budget: Option<ParallelMemoryBudget>,
    },
    /// Test-only host panic injection used to verify pool-wide failure cleanup.
    #[cfg(test)]
    Panic(Arc<std::sync::Barrier>),
}

/// The kind-matched reply channel for one job.
enum Respond {
    Task(mpsc::Sender<TaskOutcome>),
    Chunk(mpsc::Sender<ChunkOutcome>),
    Reduce(mpsc::Sender<ReduceChunkOutcome>),
    Combine(mpsc::Sender<CombineOutcome>),
}

struct Job {
    kind: JobKind,
    respond: Respond,
    /// Present only for an awaited async inner task; signalled after the reply
    /// is sent so the host pump wakes even if the reply channel was dropped.
    completion: Option<(Arc<CompletionQueue>, CompletionToken)>,
}

struct QueueState {
    jobs: VecDeque<Job>,
    closed: bool,
}

/// MPMC job queue built from `std` primitives only: a mutex-guarded deque
/// plus a condition variable, with an explicit closed flag instead of a
/// blocking `mpsc::Receiver`.
struct JobQueue {
    state: Mutex<QueueState>,
    not_empty: Condvar,
}

impl JobQueue {
    fn new() -> Self {
        Self {
            state: Mutex::new(QueueState {
                jobs: VecDeque::new(),
                closed: false,
            }),
            not_empty: Condvar::new(),
        }
    }

    /// Queue `job` and wake one waiting worker. Fails once the queue has
    /// been closed by [`Self::close`].
    fn push(&self, job: Job) -> Result<(), BackendError> {
        let mut state = self.state.lock().expect("job queue mutex is not poisoned");
        if state.closed {
            return Err(BackendError::new("execution pool is shut down"));
        }
        state.jobs.push_back(job);
        drop(state);
        self.not_empty.notify_one();
        Ok(())
    }

    /// Block until a job is available or the queue is closed and drained.
    /// Already-queued jobs are always returned before `None`, so a closed
    /// queue still lets every accepted job run to completion.
    fn pop(&self) -> Option<Job> {
        let mut state = self.state.lock().expect("job queue mutex is not poisoned");
        loop {
            if let Some(job) = state.jobs.pop_front() {
                return Some(job);
            }
            if state.closed {
                return None;
            }
            state = self
                .not_empty
                .wait(state)
                .expect("job queue mutex is not poisoned");
        }
    }

    /// Mark the queue closed and wake every worker so idle ones can exit.
    fn close(&self) {
        let mut state = self.state.lock().expect("job queue mutex is not poisoned");
        state.closed = true;
        drop(state);
        self.not_empty.notify_all();
    }

    fn is_closed(&self) -> bool {
        self.state
            .lock()
            .expect("job queue mutex is not poisoned")
            .closed
    }

    /// Fail the queue after a worker panic. Dropping queued jobs disconnects
    /// their reply channels, so every already-issued handle unblocks with a
    /// controlled error instead of waiting forever for a worker that died.
    fn abort(&self) {
        let mut state = self.state.lock().expect("job queue mutex is not poisoned");
        state.closed = true;
        state.jobs.clear();
        drop(state);
        self.not_empty.notify_all();
    }
}

fn run_job(program: &PreparedProgram, kind: JobKind, respond: Respond) {
    match (kind, respond) {
        (
            JobKind::Task {
                symbol,
                collect_stats,
                memory_policy,
            },
            Respond::Task(reply),
        ) => {
            let plain_permit = match &memory_policy {
                Some(TaskMemoryPolicy::Plain(domain)) => Some(domain.acquire()),
                _ => None,
            };
            let async_permit = match &memory_policy {
                Some(TaskMemoryPolicy::AsyncInner(domain)) => Some(domain.acquire_inner()),
                _ => None,
            };
            let (outcome, telemetry) =
                program.run_task(symbol, collect_stats, memory_policy.as_ref());
            if let Some(policy) = &memory_policy {
                match policy {
                    TaskMemoryPolicy::Plain(domain) => {
                        domain.record_outcome(&outcome, telemetry.as_ref());
                    }
                    TaskMemoryPolicy::AsyncInner(domain) => {
                        domain.record_inner_outcome(&outcome, telemetry.as_ref());
                    }
                }
            }
            drop(async_permit);
            drop(plain_permit);
            let _ = reply.send(outcome);
        }
        (
            JobKind::ForChunk {
                symbol,
                start,
                end,
                memory_budget,
            },
            Respond::Chunk(reply),
        ) => {
            let _ = reply.send(program.run_for_chunk(symbol, start, end, memory_budget.as_ref()));
        }
        (
            JobKind::ForEachChunk {
                symbol,
                base,
                values,
                range,
                memory_budget,
            },
            Respond::Chunk(reply),
        ) => {
            let _ = reply.send(program.run_for_each_chunk(
                symbol,
                base,
                &values[range],
                memory_budget.as_ref(),
            ));
        }
        (
            JobKind::ReduceChunk {
                symbol,
                base,
                identity,
                values,
                range,
                memory_budget,
            },
            Respond::Reduce(reply),
        ) => {
            let _ = reply.send(program.run_reduce_chunk(
                symbol,
                base,
                &identity,
                &values[range],
                memory_budget.as_ref(),
            ));
        }
        (
            JobKind::CombineStep {
                symbol,
                left,
                right,
                memory_budget,
            },
            Respond::Combine(reply),
        ) => {
            let _ =
                reply.send(program.run_combine_step(symbol, &left, &right, memory_budget.as_ref()));
        }
        #[cfg(test)]
        (JobKind::Panic(barrier), Respond::Task(_reply)) => {
            barrier.wait();
            panic!("simulated worker panic");
        }
        _ => {}
    }
}

/// Build this worker's `PreparedProgram` and report the outcome to the pool
/// constructor over `ready` before ever touching the job queue. On failure
/// the worker reports the cause and exits without entering the job loop.
fn worker_loop(
    module: &mir::Module,
    queue: &JobQueue,
    ready: &mpsc::Sender<Result<(), BackendError>>,
) {
    let program = match PreparedProgram::prepare(module) {
        Ok(program) => program,
        Err(error) => {
            let _ = ready.send(Err(error));
            return;
        }
    };
    if ready.send(Ok(())).is_err() {
        // The pool constructor already gave up, most likely because a
        // sibling worker failed to prepare. Nothing left to serve.
        return;
    }
    while let Some(job) = queue.pop() {
        // Nested concurrency from within a job run by this worker is not
        // supported in this version: the worker's own `PreparedProgram` never
        // registers a task runtime, so `Task.Run`/`Parallel` inside a job
        // fails with a controlled error instead of deadlocking or reaching
        // this same pool recursively. The frontend also rejects it statically.
        let Job {
            kind,
            respond,
            completion,
        } = job;
        run_job(&program, kind, respond);
        // Signal the awaited async task's completion token last, so the host
        // pump wakes even if the reply above could not be delivered.
        if let Some((queue, token)) = completion {
            queue.push(token);
        }
    }
}

/// A task in flight. Owns its own single-use result channel; no result ever
/// passes through shared or global state.
pub(super) struct TaskHandle {
    id: TaskId,
    receiver: mpsc::Receiver<TaskOutcome>,
}

impl TaskHandle {
    // Diagnostics-only accessor, currently exercised only by tests; kept for
    // the same reason `TaskId` itself exists (see its doc comment).
    #[allow(dead_code)]
    pub(super) fn id(&self) -> TaskId {
        self.id
    }

    /// Block until the task's worker responds, exactly like a normal
    /// channel receive. If the worker terminated before responding
    /// (including via an internal invariant panic, which this pool does not
    /// treat as a recoverable Aster error), this returns a controlled error
    /// instead of blocking forever or panicking.
    pub(super) fn join(self) -> Result<TaskOutcome, BackendError> {
        self.receiver.recv().map_err(|_| {
            BackendError::new(format!(
                "task {:?}'s worker disconnected before sending a result",
                self.id
            ))
        })
    }
}

/// Runs Aster MIR functions from one shared, read-only `mir::Module` across
/// a fixed set of worker threads. Not a general-purpose closure pool: every
/// job is exactly "invoke this resolved MIR function symbol."
pub(super) struct ExecutionPool {
    // Only read by `resolve`, currently exercised only by tests: today's
    // sole caller (`task_runtime::TaskRuntime`, via `execution::execute_resolved`)
    // already has its own `mir::Module` reference and resolves the entry
    // itself before the pool exists.
    #[allow(dead_code)]
    module: Arc<mir::Module>,
    queue: Arc<JobQueue>,
    // A mutex so `shutdown` can join every worker from `&self`: `submit` and
    // `shutdown` both need to be callable without consuming the pool, since
    // rejecting a post-shutdown `submit` on the same value is part of the
    // contract.
    workers: Mutex<Vec<JoinHandle<()>>>,
    max_workers: usize,
    next_task_id: AtomicU64,
}

impl ExecutionPool {
    /// Validate `module` once. Workers are prepared lazily as concurrency is
    /// actually requested, so one tiny task does not compile the module once
    /// per available CPU before doing useful work.
    pub(super) fn new(module: Arc<mir::Module>, worker_count: usize) -> Result<Self, BackendError> {
        if worker_count == 0 {
            return Err(BackendError::new(
                "execution pool requires at least one worker",
            ));
        }
        validate_module(&module)?;
        let mut workers = Vec::new();
        workers
            .try_reserve(worker_count)
            .map_err(|_| BackendError::new("execution pool worker capacity exceeds host limits"))?;
        Ok(Self {
            module,
            queue: Arc::new(JobQueue::new()),
            workers: Mutex::new(workers),
            max_workers: worker_count,
            next_task_id: AtomicU64::new(0),
        })
    }

    /// Test-only injection point: forces the worker at `failing_index` to
    /// report a simulated preparation failure instead of running
    /// `PreparedProgram::prepare`, without adding a public trait or factory.
    #[cfg(test)]
    fn new_with_failing_worker(
        module: Arc<mir::Module>,
        worker_count: usize,
        failing_index: usize,
    ) -> Result<Self, BackendError> {
        let pool = Self::new(module, worker_count)?;
        pool.ensure_workers_internal(worker_count, Some(failing_index))?;
        Ok(pool)
    }

    pub(super) fn ensure_workers(&self, worker_count: usize) -> Result<(), BackendError> {
        self.ensure_workers_internal(worker_count, None)
    }

    #[cfg(test)]
    fn prepared_worker_count(&self) -> usize {
        self.workers
            .lock()
            .expect("workers mutex is not poisoned")
            .len()
    }

    fn ensure_workers_internal(
        &self,
        worker_count: usize,
        failing_index: Option<usize>,
    ) -> Result<(), BackendError> {
        if self.queue.is_closed() {
            return Err(BackendError::new("execution pool is shut down"));
        }
        let target = worker_count.max(1).min(self.max_workers);
        let mut workers = self.workers.lock().expect("workers mutex is not poisoned");
        if workers.len() >= target {
            return Ok(());
        }
        let additional_workers = target - workers.len();
        let mut ready_receivers = Vec::new();
        ready_receivers
            .try_reserve(additional_workers)
            .map_err(|_| BackendError::new("worker preparation capacity exceeds host limits"))?;
        for index in workers.len()..target {
            let worker_module = Arc::clone(&self.module);
            let worker_queue = Arc::clone(&self.queue);
            let panic_queue = Arc::clone(&self.queue);
            let (ready_tx, ready_rx) = mpsc::channel();
            let simulate_this_worker_failing = failing_index == Some(index);
            workers.push(thread::spawn(move || {
                let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    if simulate_this_worker_failing {
                        let _ = ready_tx.send(Err(BackendError::new(
                            "simulated worker preparation failure",
                        )));
                        return;
                    }
                    worker_loop(&worker_module, &worker_queue, &ready_tx);
                }));
                if outcome.is_err() {
                    panic_queue.abort();
                }
            }));
            ready_receivers.push(ready_rx);
        }

        // Wait for every worker to confirm readiness before this pool can be
        // used, so `submit` never races a worker that has not built its
        // `PreparedProgram` yet.
        let mut failure: Option<BackendError> = None;
        for ready_rx in ready_receivers {
            let outcome = ready_rx.recv().unwrap_or_else(|_| {
                Err(BackendError::new(
                    "a worker thread terminated before completing initialization",
                ))
            });
            if let Err(error) = outcome {
                if failure.is_none() {
                    failure = Some(error);
                }
            }
        }

        if let Some(error) = failure {
            self.queue.abort();
            let failed_workers = workers.drain(..).collect::<Vec<_>>();
            drop(workers);
            for worker in failed_workers {
                let _ = worker.join();
            }
            return Err(error);
        }
        Ok(())
    }

    /// Resolve a public, zero-parameter, scalar-returning function by name
    /// to the `mir::SymbolId` [`Self::submit`] expects. Does the one textual
    /// lookup this pool ever performs; workers never look functions up by
    /// name. Currently exercised only by tests: `task_runtime::TaskRuntime`
    /// resolves `Task.Run`'s target from an already-compiled `SymbolId`
    /// baked in by codegen, never by name, but this stays available for a
    /// future direct pool caller that only has a name.
    #[allow(dead_code)]
    pub(super) fn resolve(&self, function_name: &str) -> Result<mir::SymbolId, BackendError> {
        select_entry(&self.module, function_name).map(|function| function.symbol)
    }

    /// Queue one plain or awaited `Task.Run` job that invokes `symbol` on the
    /// next free worker with its own fresh `ExecutionContext`. `completion`,
    /// present only for an awaited async inner, is signalled after the reply.
    /// Fails if the pool has been shut down.
    pub(super) fn submit(
        &self,
        symbol: mir::SymbolId,
        collect_stats: bool,
        completion: Option<(Arc<CompletionQueue>, CompletionToken)>,
    ) -> Result<TaskHandle, BackendError> {
        self.submit_task(symbol, collect_stats, None, completion)
    }

    pub(super) fn submit_governed_task(
        &self,
        symbol: mir::SymbolId,
        domain: Arc<TaskMemoryDomain>,
    ) -> Result<TaskHandle, BackendError> {
        self.submit_task(symbol, true, Some(TaskMemoryPolicy::Plain(domain)), None)
    }

    pub(super) fn submit_governed_async_inner(
        &self,
        symbol: mir::SymbolId,
        domain: Arc<AsyncMemoryDomain>,
        completion: (Arc<CompletionQueue>, CompletionToken),
    ) -> Result<TaskHandle, BackendError> {
        self.submit_task(
            symbol,
            true,
            Some(TaskMemoryPolicy::AsyncInner(domain)),
            Some(completion),
        )
    }

    fn submit_task(
        &self,
        symbol: mir::SymbolId,
        collect_stats: bool,
        memory_policy: Option<TaskMemoryPolicy>,
        completion: Option<(Arc<CompletionQueue>, CompletionToken)>,
    ) -> Result<TaskHandle, BackendError> {
        self.ensure_workers(1)?;
        let id = TaskId(self.next_task_id.fetch_add(1, Ordering::Relaxed));
        let (reply, receiver) = mpsc::channel();
        let submitted_domain = match &memory_policy {
            Some(TaskMemoryPolicy::Plain(domain)) => Some(Arc::clone(domain)),
            _ => None,
        };
        self.queue.push(Job {
            kind: JobKind::Task {
                symbol,
                collect_stats,
                memory_policy,
            },
            respond: Respond::Task(reply),
            completion,
        })?;
        if let Some(domain) = submitted_domain {
            domain.record_submission();
        }
        Ok(TaskHandle { id, receiver })
    }

    /// Queue one `Parallel` chunk and return the channel its [`ChunkOutcome`]
    /// arrives on. Parallel chunks never carry a completion token.
    pub(super) fn submit_parallel(
        &self,
        kind: JobKind,
    ) -> Result<mpsc::Receiver<ChunkOutcome>, BackendError> {
        let (reply, receiver) = mpsc::channel();
        self.queue.push(Job {
            kind,
            respond: Respond::Chunk(reply),
            completion: None,
        })?;
        Ok(receiver)
    }

    /// Queue one `Parallel.Reduce` accumulation chunk and return the channel
    /// its [`ReduceChunkOutcome`] arrives on.
    pub(super) fn submit_reduce_chunk(
        &self,
        kind: JobKind,
    ) -> Result<mpsc::Receiver<ReduceChunkOutcome>, BackendError> {
        let (reply, receiver) = mpsc::channel();
        self.queue.push(Job {
            kind,
            respond: Respond::Reduce(reply),
            completion: None,
        })?;
        Ok(receiver)
    }

    /// Queue one `Parallel.Reduce` combine step and return the channel its
    /// [`CombineOutcome`] arrives on. Callers submit these one at a time,
    /// waiting for each result before submitting the next, so the sequential
    /// combination phase never runs two `Combine` calls of the same
    /// reduction concurrently.
    pub(super) fn submit_combine_step(
        &self,
        kind: JobKind,
    ) -> Result<mpsc::Receiver<CombineOutcome>, BackendError> {
        let (reply, receiver) = mpsc::channel();
        self.queue.push(Job {
            kind,
            respond: Respond::Combine(reply),
            completion: None,
        })?;
        Ok(receiver)
    }

    #[cfg(test)]
    fn submit_panicking(
        &self,
        barrier: Arc<std::sync::Barrier>,
    ) -> Result<TaskHandle, BackendError> {
        let id = TaskId(self.next_task_id.fetch_add(1, Ordering::Relaxed));
        let (reply, receiver) = mpsc::channel();
        self.queue.push(Job {
            kind: JobKind::Panic(barrier),
            respond: Respond::Task(reply),
            completion: None,
        })?;
        Ok(TaskHandle { id, receiver })
    }

    /// Stop accepting new tasks, let every already-accepted task finish, and
    /// wait for every worker thread to exit. Idempotent: calling it again,
    /// or dropping the pool afterward, joins an already-empty worker list.
    /// A `submit` call after this returns fails.
    pub(super) fn shutdown(&self) {
        self.queue.close();
        let mut workers = self.workers.lock().expect("workers mutex is not poisoned");
        for worker in workers.drain(..) {
            let _ = worker.join();
        }
    }
}

impl Drop for ExecutionPool {
    fn drop(&mut self) {
        self.shutdown();
    }
}

#[cfg(test)]
mod tests {
    #[cfg(feature = "aarm-telemetry")]
    use std::sync::atomic::AtomicUsize;
    use std::time::Duration;

    use super::*;

    const TEST_TIMEOUT: Duration = Duration::from_secs(5);

    fn compile(source: &str) -> mir::Module {
        aster_compiler::compile(source)
            .expect("source compiles")
            .mir
    }

    /// Calls the real (blocking) `TaskHandle::join` on a helper thread and
    /// bounds the wait from here, so a stuck worker fails the test instead
    /// of hanging it. Callers use this only where a clean completion is
    /// expected; a channel-level failure here is itself a test bug.
    fn join_with_timeout(handle: TaskHandle) -> TaskOutcome {
        let id = handle.id();
        let (sender, receiver) = mpsc::channel();
        thread::spawn(move || {
            let _ = sender.send(handle.join());
        });
        receiver
            .recv_timeout(TEST_TIMEOUT)
            .unwrap_or_else(|_| panic!("task {id:?} did not respond before the test timeout"))
            .unwrap_or_else(|error| panic!("task {id:?} channel failed: {error}"))
    }

    /// `JobKind` (what a worker actually receives) must stay `Send + 'static`
    /// with no raw pointer, `ExecutionContext`, or `PreparedProgram` inside
    /// it. This is a compile-time guarantee, not a runtime assertion: a
    /// future variant carrying `*mut aster_runtime::ExecutionContext` or a
    /// borrowed array pointer would make `JobKind` stop being `Send` (raw
    /// pointers are not `Send`) and this test would fail to *compile*, not
    /// just fail to pass. `ExecutionValue` (the only thing `ForEachChunk`
    /// carries per element) is scalar-only, never a class/array/interface
    /// handle (see `values::primitive`).
    #[test]
    fn job_kind_carries_only_owned_send_data_no_arena_pointer_or_context() {
        fn assert_send<T: Send>() {}
        assert_send::<JobKind>();
        assert_send::<ParallelMemoryBudget>();
        assert_send::<ChunkOutcome>();
        assert_send::<TaskOutcome>();
        assert_send::<Arc<Vec<ExecutionValue>>>();
        // `Parallel.Reduce`'s job/outcome types must hold to the same
        // guarantee: only owned scalars, never a pointer or `ExecutionContext`.
        assert_send::<ReduceChunkOutcome>();
        assert_send::<CombineOutcome>();
        assert_send::<TaskMemoryPolicy>();
    }

    #[cfg(feature = "aarm-telemetry")]
    #[test]
    fn async_domain_counts_move_next_and_inner_overlap_without_precharging() {
        let page = aster_runtime::ExecutionContext::AARM_MIN_PAGE_CAPACITY_BYTES;
        let governor = Arc::new(aster_runtime::MemoryGovernor::new(2 * page));
        let domain = Arc::new(AsyncMemoryDomain::new(Arc::clone(&governor), page, page));
        let move_permit = domain.acquire_move_next();
        let move_context = aster_runtime::ExecutionContext::with_async_move_next_memory_budget(
            Arc::clone(domain.governor()),
            domain.move_next_limit_bytes(),
        );
        assert_eq!(governor.telemetry().current_capacity_bytes, 0);
        let inner_domain = Arc::clone(&domain);
        let entered = Arc::new(std::sync::Barrier::new(2));
        let release = Arc::new(std::sync::Barrier::new(2));
        let inner_entered = Arc::clone(&entered);
        let inner_release = Arc::clone(&release);
        let inner = thread::spawn(move || {
            let _permit = inner_domain.acquire_inner();
            let context = aster_runtime::ExecutionContext::with_async_inner_memory_budget(
                Arc::clone(inner_domain.governor()),
                inner_domain.inner_limit_bytes(),
            );
            inner_entered.wait();
            inner_release.wait();
            drop(context);
        });
        entered.wait();
        let counters = domain.counters();
        assert_eq!(counters.peak_live_contexts, 2);
        release.wait();
        drop(move_context);
        drop(move_permit);
        inner.join().expect("inner context completes");
        let counters = domain.counters();
        assert_eq!(counters.move_next_contexts_started, 1);
        assert_eq!(counters.move_next_contexts_completed, 1);
        assert_eq!(counters.inner_contexts_started, 1);
        assert_eq!(counters.inner_contexts_completed, 1);
        assert_eq!(governor.telemetry().current_capacity_bytes, 0);
    }

    #[cfg(feature = "aarm-telemetry")]
    #[test]
    fn async_domain_counts_role_specific_memory_failures() {
        let governor = Arc::new(aster_runtime::MemoryGovernor::new(0));
        let domain = AsyncMemoryDomain::new(governor, 0, 0);
        let move_error = Err(BackendError::new(
            "Aster runtime error: allocation exceeds the deterministic async MoveNext memory entitlement of 0 bytes",
        ));
        domain.record_move_next_outcome(&move_error, None);
        let inner_error = TaskOutcome::Failed(BackendError::new(
            "Aster runtime error: allocation exceeds the deterministic async awaited-inner memory entitlement of 0 bytes",
        ));
        domain.record_inner_outcome(&inner_error, None);
        let counters = domain.counters();
        assert_eq!(counters.move_next_memory_failures, 1);
        assert_eq!(counters.inner_memory_failures, 1);
    }

    #[cfg(feature = "aarm-telemetry")]
    fn assert_task_domain_context_cap(
        physical_workers: usize,
        memory_concurrency: usize,
        queued_tasks: usize,
    ) {
        let governor = Arc::new(aster_runtime::MemoryGovernor::new(64 * 1024));
        let domain = Arc::new(TaskMemoryDomain::new(
            Arc::clone(&governor),
            64 * 1024,
            memory_concurrency,
        ));
        let live_contexts = Arc::new(AtomicUsize::new(0));
        let peak_contexts = Arc::new(AtomicUsize::new(0));
        let completed = Arc::new(AtomicUsize::new(0));
        let (entered_sender, entered_receiver) = mpsc::channel();
        let release = Arc::new((Mutex::new(false), Condvar::new()));
        let mut workers = Vec::with_capacity(physical_workers);

        for _ in 0..physical_workers {
            let domain = Arc::clone(&domain);
            let live_contexts = Arc::clone(&live_contexts);
            let peak_contexts = Arc::clone(&peak_contexts);
            let completed = Arc::clone(&completed);
            let entered_sender = entered_sender.clone();
            let release = Arc::clone(&release);
            workers.push(thread::spawn(move || {
                for _ in 0..(queued_tasks / physical_workers) {
                    let permit = domain.acquire();
                    let context = aster_runtime::ExecutionContext::with_task_memory_budget(
                        Arc::clone(domain.governor()),
                        domain.local_limit_bytes(),
                    );
                    let live = live_contexts.fetch_add(1, Ordering::SeqCst) + 1;
                    peak_contexts.fetch_max(live, Ordering::SeqCst);
                    entered_sender.send(()).expect("observer remains live");
                    let (lock, wake) = &*release;
                    let mut released = lock.lock().expect("release mutex is not poisoned");
                    while !*released {
                        released = wake.wait(released).expect("release mutex is not poisoned");
                    }
                    drop(context);
                    live_contexts.fetch_sub(1, Ordering::SeqCst);
                    drop(permit);
                    completed.fetch_add(1, Ordering::SeqCst);
                }
            }));
        }
        drop(entered_sender);

        for _ in 0..memory_concurrency {
            entered_receiver
                .recv_timeout(TEST_TIMEOUT)
                .expect("each permitted governed context starts");
        }
        assert_eq!(live_contexts.load(Ordering::SeqCst), memory_concurrency);
        assert_eq!(peak_contexts.load(Ordering::SeqCst), memory_concurrency);
        assert!(
            entered_receiver
                .recv_timeout(Duration::from_millis(25))
                .is_err(),
            "a queued task began a governed context above the memory cap"
        );

        let (lock, wake) = &*release;
        *lock.lock().expect("release mutex is not poisoned") = true;
        wake.notify_all();
        for worker in workers {
            worker.join().expect("bounded task worker completes");
        }
        assert_eq!(completed.load(Ordering::SeqCst), queued_tasks);
        assert_eq!(peak_contexts.load(Ordering::SeqCst), memory_concurrency);
        assert_eq!(live_contexts.load(Ordering::SeqCst), 0);
    }

    #[test]
    #[cfg(feature = "aarm-telemetry")]
    fn task_domain_cap_structurally_limits_eight_workers_to_two_live_contexts() {
        assert_task_domain_context_cap(8, 2, 8);
    }

    #[test]
    #[cfg(feature = "aarm-telemetry")]
    fn task_domain_one_slot_serializes_multiple_queued_contexts() {
        assert_task_domain_context_cap(4, 1, 8);
    }

    #[test]
    fn impossible_worker_capacity_is_a_controlled_error() {
        let module = Arc::new(compile("public int Run() { return 42; }"));
        let result = ExecutionPool::new(module, usize::MAX);
        assert!(result.is_err_and(|error| error.message().contains("worker capacity")));
    }

    #[test]
    fn single_worker_pool_runs_a_task() {
        let module = Arc::new(compile("public int Run() { return 40 + 2; }"));
        let pool = ExecutionPool::new(module, 1).expect("pool starts");
        assert_eq!(pool.prepared_worker_count(), 0);
        let run = pool.resolve("Run").expect("Run resolves");

        let handle = pool.submit(run, false, None).expect("task is accepted");
        assert_eq!(pool.prepared_worker_count(), 1);
        match join_with_timeout(handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(42)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn worker_demand_is_capped_before_allocating_preparation_state() {
        let module = Arc::new(compile("public int Run() { return 42; }"));
        let pool = ExecutionPool::new(module, 1).expect("pool starts");

        pool.ensure_workers(usize::MAX)
            .expect("demand is capped by the configured worker limit");
        assert_eq!(pool.prepared_worker_count(), 1);

        pool.shutdown();
    }

    #[test]
    fn multiple_workers_run_many_tasks_of_the_same_function() {
        let module = Arc::new(compile("public int Run() { return 40 + 2; }"));
        let pool = ExecutionPool::new(module, 4).expect("pool starts");
        pool.ensure_workers(4).expect("four workers prepare");
        assert_eq!(pool.prepared_worker_count(), 4);
        let run = pool.resolve("Run").expect("Run resolves");

        let handles: Vec<_> = (0..20)
            .map(|_| pool.submit(run, false, None).expect("task is accepted"))
            .collect();

        for handle in handles {
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(42)),
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn workers_run_different_functions_of_the_same_module_regardless_of_completion_order() {
        let module = Arc::new(compile(
            "public int Answer() { return 42; } public int Double(int value) { return value * 2; } public int Run() { return Double(Answer()); }",
        ));
        let pool = ExecutionPool::new(module, 3).expect("pool starts");
        let answer = pool.resolve("Answer").expect("Answer resolves");
        let run = pool.resolve("Run").expect("Run resolves");

        // Submitted out of the order results are asserted in, so a pass
        // proves results are matched to their own task, not to arrival order.
        let run_handle = pool.submit(run, false, None).expect("task is accepted");
        let answer_handle = pool.submit(answer, false, None).expect("task is accepted");

        match join_with_timeout(answer_handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(42)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }
        match join_with_timeout(run_handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(84)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn each_task_gets_independent_non_accumulating_metrics() {
        let module = Arc::new(compile(
            "public int Run() { int[] values = [20, 22]; return values[0] + values[1]; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let handles: Vec<_> = (0..6)
            .map(|_| pool.submit(run, true, None).expect("task is accepted"))
            .collect();

        for handle in handles {
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, stats) => {
                    assert_eq!(value, ExecutionValue::Int(42));
                    assert_eq!(stats.total_allocations, 1);
                    assert_eq!(stats.array_allocations, 1);
                    // No persistent leftover from any other task's arena and
                    // the temporary array is fully rewound before return.
                    assert_eq!(stats.used_bytes, 0);
                }
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn a_controlled_error_in_one_task_does_not_block_later_tasks() {
        let module = Arc::new(compile(
            "public int Failing() { int[] values = new int[1]; return values[5]; } public int Ok() { return 1; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let failing = pool.resolve("Failing").expect("Failing resolves");
        let ok = pool.resolve("Ok").expect("Ok resolves");

        let failing_handle = pool.submit(failing, false, None).expect("task is accepted");
        let ok_handle = pool.submit(ok, false, None).expect("task is accepted");

        match join_with_timeout(failing_handle) {
            TaskOutcome::Failed(error) => assert!(error.message().contains("array index 5")),
            TaskOutcome::Completed(..) => panic!("expected a controlled runtime error"),
        }
        match join_with_timeout(ok_handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(1)),
            TaskOutcome::Failed(error) => panic!("unaffected task failed: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn shutdown_still_runs_every_already_accepted_job() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let handles: Vec<_> = (0..10)
            .map(|_| pool.submit(run, false, None).expect("task is accepted"))
            .collect();

        // Nothing has been joined yet: every job is still only queued or
        // in flight when shutdown begins draining the queue.
        pool.shutdown();

        for handle in handles {
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(1)),
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }
    }

    #[test]
    fn submitting_after_shutdown_fails() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 1).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        pool.shutdown();

        let result = pool.submit(run, false, None);
        assert!(result.is_err());
    }

    #[test]
    fn many_temporary_tasks_across_multiple_workers_all_end_with_zero_used_bytes() {
        let module = Arc::new(compile(
            "public int Run() { int[] values = [20, 22]; return values[0] + values[1]; }",
        ));
        let pool = ExecutionPool::new(module, 4).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let handles: Vec<_> = (0..24)
            .map(|_| pool.submit(run, true, None).expect("task is accepted"))
            .collect();

        for handle in handles {
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, stats) => {
                    assert_eq!(value, ExecutionValue::Int(42));
                    assert_eq!(stats.used_bytes, 0);
                }
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn many_persistent_tasks_on_one_worker_do_not_accumulate_memory() {
        let module = Arc::new(compile(
            "public interface IBox { int Get(); } public class Box : IBox { public int value; public int Get() { return value; } } public int Run() { Box box = new Box(); box.value = 1; IBox view = box; return view.Get(); }",
        ));
        // A single worker serializes every task, so this is the strictest
        // check that persistent storage from one task never leaks into the
        // next one on the same thread.
        let pool = ExecutionPool::new(module, 1).expect("pool starts");
        let run = pool.resolve("Run").expect("Run resolves");

        let mut expected_used_bytes = None;
        for _ in 0..15 {
            let handle = pool.submit(run, true, None).expect("task is accepted");
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, stats) => {
                    assert_eq!(value, ExecutionValue::Int(1));
                    assert!(stats.used_bytes > 0);
                    let expected = *expected_used_bytes.get_or_insert(stats.used_bytes);
                    assert_eq!(stats.used_bytes, expected);
                }
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn interleaved_temporary_and_persistent_tasks_keep_independent_stats() {
        let module = Arc::new(compile(
            "public interface IBox { int Get(); } public class Box : IBox { public int value; public int Get() { return value; } } public int Persistent() { Box box = new Box(); box.value = 1; IBox view = box; return view.Get(); } public int Temporary() { int[] values = [20, 22]; return values[0] + values[1]; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let persistent = pool.resolve("Persistent").expect("Persistent resolves");
        let temporary = pool.resolve("Temporary").expect("Temporary resolves");

        for round in 0..8 {
            let symbol = if round % 2 == 0 {
                persistent
            } else {
                temporary
            };
            let handle = pool.submit(symbol, true, None).expect("task is accepted");
            match join_with_timeout(handle) {
                TaskOutcome::Completed(value, stats) => {
                    if round % 2 == 0 {
                        assert_eq!(value, ExecutionValue::Int(1));
                        assert!(stats.used_bytes > 0);
                    } else {
                        assert_eq!(value, ExecutionValue::Int(42));
                        assert_eq!(stats.used_bytes, 0);
                    }
                }
                TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
            }
        }

        pool.shutdown();
    }

    #[test]
    fn a_controlled_error_between_two_valid_tasks_does_not_affect_either() {
        let module = Arc::new(compile(
            "public int Ok() { return 7; } public int Failing() { int[] values = new int[1]; return values[5]; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let ok = pool.resolve("Ok").expect("Ok resolves");
        let failing = pool.resolve("Failing").expect("Failing resolves");

        let first = pool.submit(ok, false, None).expect("task is accepted");
        let middle = pool.submit(failing, false, None).expect("task is accepted");
        let last = pool.submit(ok, false, None).expect("task is accepted");

        match join_with_timeout(first) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(7)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }
        match join_with_timeout(middle) {
            TaskOutcome::Failed(error) => assert!(error.message().contains("array index 5")),
            TaskOutcome::Completed(..) => panic!("expected a controlled runtime error"),
        }
        match join_with_timeout(last) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(7)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn dropping_one_tasks_outcome_does_not_affect_another() {
        let module = Arc::new(compile(
            "public int First() { return 11; } public int Second() { return 22; }",
        ));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");
        let first_symbol = pool.resolve("First").expect("First resolves");
        let second_symbol = pool.resolve("Second").expect("Second resolves");

        let first_handle = pool
            .submit(first_symbol, false, None)
            .expect("task is accepted");
        let second_handle = pool
            .submit(second_symbol, false, None)
            .expect("task is accepted");

        let first_outcome = join_with_timeout(first_handle);
        drop(first_outcome);

        match join_with_timeout(second_handle) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(22)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool.shutdown();
    }

    #[test]
    fn multiple_independent_pools_do_not_interfere() {
        let module_a = Arc::new(compile("public int Run() { return 1; }"));
        let module_b = Arc::new(compile("public int Run() { return 2; }"));

        let pool_a = ExecutionPool::new(module_a, 1).expect("pool a starts");
        let pool_b = ExecutionPool::new(module_b, 1).expect("pool b starts");
        let run_a = pool_a.resolve("Run").expect("Run resolves in a");
        let run_b = pool_b.resolve("Run").expect("Run resolves in b");

        let handle_a = pool_a.submit(run_a, false, None).expect("task is accepted");
        let handle_b = pool_b.submit(run_b, false, None).expect("task is accepted");

        match join_with_timeout(handle_a) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(1)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        // Shutting down one pool must not disturb the other.
        pool_a.shutdown();

        match join_with_timeout(handle_b) {
            TaskOutcome::Completed(value, _) => assert_eq!(value, ExecutionValue::Int(2)),
            TaskOutcome::Failed(error) => panic!("unexpected failure: {error}"),
        }

        pool_b.shutdown();
    }

    #[test]
    fn shutdown_with_an_empty_queue_terminates_cleanly() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 3).expect("pool starts");

        pool.shutdown();

        assert!(
            pool.submit(pool.resolve("Run").expect("Run resolves"), false, None)
                .is_err()
        );
    }

    #[test]
    fn shutdown_is_idempotent_and_drop_does_not_rejoin_workers() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 2).expect("pool starts");

        pool.shutdown();
        // Calling it again must not try to join an already-joined
        // `JoinHandle`, and the pool's own `Drop` will call it once more.
        pool.shutdown();

        let run = pool.resolve("Run").expect("Run resolves");
        assert!(pool.submit(run, false, None).is_err());
    }

    #[test]
    fn worker_initialization_failure_returns_a_controlled_error_without_a_partial_pool() {
        let module = Arc::new(compile("public int Run() { return 1; }"));

        let result = ExecutionPool::new_with_failing_worker(module, 3, 1);

        match result {
            Err(error) => assert!(error.message().contains("simulated worker preparation")),
            Ok(_) => panic!("a failed worker must fail the whole pool"),
        }
    }

    #[test]
    fn join_returns_a_controlled_error_when_the_response_channel_disconnects() {
        let (sender, receiver) = mpsc::channel::<TaskOutcome>();
        let handle = TaskHandle {
            id: TaskId(0),
            receiver,
        };
        drop(sender);

        let result = handle.join();
        assert!(result.is_err());
    }

    #[test]
    fn worker_panic_disconnects_queued_jobs_and_closes_the_pool() {
        let module = Arc::new(compile("public int Run() { return 1; }"));
        let pool = ExecutionPool::new(module, 1).expect("pool starts");
        let barrier = Arc::new(std::sync::Barrier::new(2));
        let panicking = pool
            .submit_panicking(Arc::clone(&barrier))
            .expect("panic job is accepted");
        let queued = pool
            .submit(pool.resolve("Run").expect("Run resolves"), false, None)
            .expect("second job is queued before the panic");

        barrier.wait();

        assert!(panicking.join().is_err());
        assert!(queued.join().is_err());
        assert!(
            pool.submit(pool.resolve("Run").expect("Run resolves"), false, None)
                .is_err()
        );
    }

    #[test]
    fn transported_types_are_thread_transferable() {
        fn assert_send<T: Send>() {}
        fn assert_send_sync<T: Send + Sync>() {}

        assert_send_sync::<mir::Module>();
        assert_send::<TaskOutcome>();
        assert_send::<BackendError>();
        assert_send::<crate::MemoryStats>();
        assert_send::<Result<TaskOutcome, BackendError>>();
        // `JobKind::ForEachChunk` carries only owned `ExecutionValue` scalars,
        // never a pointer into any host arena or `ExecutionContext`: this is
        // the structural guarantee behind "no array pointer ever reaches a
        // worker" (see `async_abi::copy_scalar_array`), checked at the type
        // level rather than by inspecting job contents at runtime.
        assert_send::<JobKind>();
        assert_send::<ChunkOutcome>();
    }

    #[test]
    fn for_each_chunks_share_only_immutable_host_owned_scalars() {
        let values = Arc::new(vec![
            crate::ExecutionValue::Int(1),
            crate::ExecutionValue::Int(2),
        ]);
        let chunk = JobKind::ForEachChunk {
            symbol: mir::SymbolId(0),
            base: 0,
            values: Arc::clone(&values),
            range: 0..1,
            memory_budget: None,
        };
        let JobKind::ForEachChunk {
            values: shared,
            range,
            ..
        } = chunk
        else {
            unreachable!()
        };
        assert!(Arc::ptr_eq(&values, &shared));
        assert_eq!(&shared[range], [crate::ExecutionValue::Int(1)]);
    }
}
